### ISSUE TITLE
URLs plugin - Allow registering handlers for other protocols

### ISSUE THREAD

**Issue by rakiru** [UltrosBot/Ultros#62]
Currently, the URLs plugin supports `http` and `https` protocol links. This could be extended by allowing other plugins to register handlers for arbitrary protocols, such as `ftp` or `spotify`. An advantage of this is a single place where link extraction is done, resulting in more consistency in weird cases (see #61), and stops multiple plugins having to reimplement the same logic.

**Comment by gdude2002** [comment]
This is related to #61 which will allow us to detect based on all kinds of stuff.

**Comment by gdude2002** [comment]
Closed in favour of #69
