### ISSUE TITLE
Log level command line args

### ISSUE THREAD

**Issue by rakiru** [UltrosBot/Ultros#72]
`--debug` and `--trace` were removed in the switch to logbook. They should either be reimplemented, or an optional log config parameter should be added (`--logconf="logging-debug.yml"` or something).

**Comment by gdude2002** [comment]
Roger, Mr. Sean Gordon Freeman

**Comment by gdude2002** [comment]
Fixed in https://github.com/UltrosBot/Ultros/compare/5d011c957c2b...5b0a4d0dd921
